const interesses = [
  "Pensamento Computacional",
  "Matemática Básica",
  "Leitura e Produção de Textos",
  "Inglês",
  "Ética, Cidadania e Sociedade",
  "Projetos e métodos para a produção do conhecimento",
  "Algoritmos e Programação de Computadores I",
  "Algoritmos e Programação de Computadores II",
  "Cálculo I",
  "Fundamentos Matemáticos para Computação",
  "Introdução a Conceitos de Computação",
  "Fundamentos de Internet e Web",
  "Sistemas Computacionais",
  "Estatística e Probabilidade",
  "Estruturas de Dados",
  "Programação Orientada a Objetos",
  "Formação Profissional em Computação",
  "Gestão da Inovação e Desenvolvimento de Produtos",
  "Banco de Dados",
  "Bancos de Dados",
  "Desenvolvimento web",
  "Introdução a Ciência de Dados",
  "Engenharia de Software",
  "Geometria Analítica e Álgebra Linear",
  "Modelagem e Inferência Estatística",
  "Mineração de Dados",
  "Infraestrutura para Sistemas de Software",
  "Computação Escalável",
  "Visualização Computacional",
  "Aprendizado de Máquinas",
  "Impactos da Computação na Sociedade",
  "Visão Computacional",
  "Redes Neurais",
  "Aprendizado Profundo",
  "Segurança da Informação",
  "Planejamento Estratégico de Negócios",
  "Processamento de Linguagem Natural",
  "Física do Movimento",
  "Circuitos Digitais",
  "Protocolos de Comunicação IoT",
  "Sistemas Embarcados",
  "Plataforma de Ingestão e Análise de Dados",
  "Interface Humano-Computador",
  "Mecânica dos Sólidos e dos Fluidos",
  "Processamento Digital de Sinais",
  "Projeto e Análise de Algoritmos",
  "Desenvolvimento para Dispositivos Móveis",
  "Química Tecnológica e Ambiental",
  "Controle e Automação",
  "Compiladores",
  "Cidades Inteligentes",
  "Legislação e Responsabilidade Profissional",
];

export default interesses;
